apiVersion: v1
kind: Pod
metadata:
  name: busybox-1
  labels:
    app: busybox-1
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo The secret is: ${PASSWORD}; sleep 3600"]
      env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-2
  labels:
    app: busybox-2
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo The secret is: ${PASSWORD}; sleep 3600"]
      env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
